-- Supabase SQL Editorで実行する初期設定。
-- 既存プロジェクトへ相乗りしても衝突しにくいよう、テーブル名にorienteering_を付けています。

create table if not exists public.orienteering_courses (
  id bigint generated by default as identity primary key,
  title text not null,
  duration text not null default '',
  distance text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orienteering_checkpoints (
  id bigint generated by default as identity primary key,
  course_id bigint not null references public.orienteering_courses(id) on delete cascade,
  name text not null,
  lat double precision not null check (lat between -90 and 90),
  lng double precision not null check (lng between -180 and 180),
  points integer not null default 0 check (points >= 0),
  distance text not null default '',
  category text not null default '',
  hint text not null default '',
  mission text not null default '',
  explain text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orienteering_courses enable row level security;
alter table public.orienteering_checkpoints enable row level security;

-- 参加者は公開中のコースとチェックポイントを読むだけです。
create policy "orienteering courses are publicly readable"
on public.orienteering_courses for select
to anon, authenticated
using (is_active = true);

create policy "orienteering checkpoints are publicly readable"
on public.orienteering_checkpoints for select
to anon, authenticated
using (
  exists (
    select 1 from public.orienteering_courses c
    where c.id = course_id and c.is_active = true
  )
);

-- 管理者としてSupabase Authへ登録されたユーザーだけが編集できます。
-- 試作では認証済みユーザー全員を管理者として扱うため、参加者アカウントは作りません。
create policy "authenticated users manage orienteering courses"
on public.orienteering_courses for all
to authenticated
using (true)
with check (true);

create policy "authenticated users manage orienteering checkpoints"
on public.orienteering_checkpoints for all
to authenticated
using (true)
with check (true);

-- 初期コースと5地点。重複投入を避けるため、コースが空の場合だけ実行します。
do $$
declare new_course_id bigint;
begin
  if not exists (select 1 from public.orienteering_courses) then
    insert into public.orienteering_courses(title, duration, distance)
    values ('ひばりヶ丘・地形とまちの変化を歩く', '約75分', '約3.0km')
    returning id into new_course_id;

    insert into public.orienteering_checkpoints
      (course_id,name,lat,lng,points,distance,category,hint,mission,explain,sort_order)
    values
      (new_course_id,'ひばりヶ丘駅の表と裏',35.7515231,139.5455333,20,'スタート地点','交通・都市','駅の北口と南口を見比べられる場所から、道幅や建物の並びを観察します。','北口と南口で、駅前の風景が最も違うと感じた点を1つ記録してください。','鉄道駅は同じ駅でも出口ごとに道路、商業、住宅の配置が異なります。駅を境にした街の成り立ちを読む入口です。',1),
      (new_course_id,'ひばりヶ丘公園と駅前の余白',35.7520648,139.5432675,25,'約250m','土地利用','駅や線路に近い公園です。周囲の住宅・店舗・線路との位置関係を見てみよう。','この場所が公園であることで、駅前の街にどんな役割を果たしていると思いますか？','地図上の緑地は、休憩場所だけでなく、周辺の建物密度や人の流れを観察する手がかりにもなります。',2),
      (new_course_id,'「谷戸」の地名を読む',35.7476968,139.5421435,30,'約650m','地名・地形','谷戸イチョウ公園の周辺。駅から歩いてきた道の傾きも思い出してみよう。','「谷戸」という地名から想像する地形と、実際に歩いた感覚が一致するか記録してください。','地名は過去の地形や土地利用を考える手がかりです。現地の起伏や古地図と合わせて確かめます。',3),
      (new_course_id,'ひばりが丘団地の配置',35.7452253,139.5365957,40,'約1.3km','団地・都市計画','建物の向き、棟と棟の間隔、歩行者の道、緑の置かれ方に注目。','一般的な駅前の住宅地と違うと感じた「団地ならではの配置」を1つ見つけてください。','大規模団地では、道路、緑地、生活施設をまとめて計画した空間構成を観察できます。',4),
      (new_course_id,'谷戸せせらぎ公園の水と低地',35.7431216,139.5444632,35,'約1.2km','水・微地形','公園の水辺と周囲の高さ、道路の傾きを見比べてみよう。','水がこの場所にある理由を、周囲の高低差から仮説として書いてください。','水辺の位置と地形には関係があることがあります。現地観察から仮説を立て、資料で確かめる題材にします。',5);
  end if;
end $$;
